eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8088/eureka/
server: 
  port: 8091
spring: 
  application: 
    name: service-feign
  zipkin: 
    base-url: http://localhost:9411
feign: 
  hystrix: 
    enabled: true
