server: 
  port: 8088
spring:
  application:
    name: eureka-server
eureka:
  server: 
    enable-self-preservation: false	# 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 3000 # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:8088/eureka/