spring: 
  rabbitmq: 
    host: localhost
    port: 5672
  cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: config-server
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8088/eureka/